server:
  port: 8080
  servlet:
    context-path: /inno

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/innovation?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    hikari:
        idle-timeout: 60000
        maximum-pool-size: 30
        minimum-idle: 10
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappering/*.xml

logging:
  level:
    root: INFO
    org: WARN
    io: WARN
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-30logger{1}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

